
version: "3.8"

services:
  accounts:
    env_file:
      - ./accounts/.env
    build: ./accounts
    volumes:
      - ./accounts:/accounts
    ports:
      - "8000:8000"

    depends_on:
      - accounts-db
    environment:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}

  accounts-db:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}


